language: node_js
node_js: [4, 6, 8]

os: [linux, osx]
dist: trusty
sudo: required

env:
  - TEST=jest
  - EXAMPLE=client-only-paths
  - EXAMPLE=gatsbygram
  - EXAMPLE=hn
  - EXAMPLE=image-processing
  - EXAMPLE=no-plugins
  - EXAMPLE=no-trailing-slashes
  - EXAMPLE=using-drupal
  - EXAMPLE=using-postcss-sass

cache:
  directories:
    - $(npm config get cache)

before_install:
  - npm i -g npm@5

install:
  - npm install

script:
  # only run the overall test script on one build
  - if [[ $TEST ]]; then npm test; fi

  # for all the others, install/test their site
  - if [[ $EXAMPLE ]]; then npm install -g gatsby-dev-cli@canary; fi
  - if [[ $EXAMPLE ]]; then cd "examples/$EXAMPLE"; fi
  - if [[ $EXAMPLE ]]; then npm install; fi
  - if [[ $EXAMPLE ]]; then gatsby-dev --set-path-to-repo ../..; fi
  - if [[ $EXAMPLE ]]; then gatsby-dev --scan-once; fi
  - if [[ $EXAMPLE ]]; then npm test; fi
  - if [[ $EXAMPLE ]]; then npm run build; fi
