language: node_js
dist: trusty
sudo: false

node_js:
  - "4"
  - "6"
  - "7"

os: [linux, osx]

before_install:
  - git submodule update --init --recursive
  - npm i -g npm@5
  - npm config set python `which python`

install:
  - npm install

script:
  - npm test
